service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  iamRoleStatements: ${file(IAM/DynamoDB.yml)}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Access-Control-Allow-Headers
        - Authorization
        - Content-Type
      allowedMethods:
        - GET
        - PUT
        - DELETE
        - OPTIONS
        - HEAD
        - POST
      maxAge: 600
      allowCredentials: true
  authorizer:
      name: CognitoAuthorizer
      identitySource: $request.header.Authorization
      issuerUrl: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_u6frR8F8q
      audience: serverlesstodoappfro2751e006_userpool_2751e006-logintodo  

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /addTodo
          method: post
          
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - http:
          path: /fetchTodos
          method: get
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - http:
          path: /fetchTodo/{id}
          method: get
  editTodo:
    handler: src/editTodo.handler
    events:
      - http:
          path: /editTodo/{id}
          method: put
  updateCompleted:
    handler: src/updateCompleted.handler
    events:
      - http:
          path: /updateCompleted/{id}
          method: put
  deleteTodo:
    handler: src/deleteTodo.handler
    events:
      - http:
          path: /deleteTodo/{id}
          method: delete

resources:
  Resources:
    NewTodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NewTodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins: 
  - serverless-offline
  - serverless-aws-documentation

custom:
  serverless-offline:
    useChildProcesses: true
    noAuth: true
    httpPort: 3009